# Generated by Django 4.2.3 on 2023-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
