# Generated by Django 4.2.3 on 2023-08-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productdetail_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetail',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='uploads/product/'),
        ),
    ]
