# Generated by Django 4.2.3 on 2023-08-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycategory_inventorydetail_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydetail',
            name='price_per_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
